#!/bin/sh
#
# As of 0.13, xmonad --recompile will look for a custom build script.

set -e

EXTRA_ARGS=
if [ -f /tmp/.xmonad-nooptimize ]
then
    EXTRA_ARGS=--fast
fi

stack build :my-xmonad --verbosity error $EXTRA_ARGS
stack install :my-xmonad --local-bin-path bin/ --verbosity error $EXTRA_ARGS
mv bin/my-xmonad "$1"

rm -f /tmp/.xmonad-nooptimize
