#!/bin/sh -e

out="$1"

! [ -f "$HOME/.xmonad/recompilation-success" ] && [ -f "$out" ] && exit 0 || true

stack build :my-xmonad --verbosity error
stack install :my-xmonad --local-bin-path bin/ --verbosity error

mv bin/my-xmonad "$out"
