name:                csillag-xmonad
version:             0.1.0.0
author:              "Daniel Csillag"
copyright:           "2021 Daniel Csillag"

description:         My XMonad configs

dependencies:
- base >= 4.7 && < 5
- xmonad >= 0.17
- xmonad-contrib >= 0.17
- containers
- directory
- aeson
- utf8-string
- process

ghc-options:
- -Wall
- -Wno-missing-signatures
- -fwrite-ide-info # for weeder

library:
  source-dirs: src

executables:
  my-xmonad:
    main: xmonad.hs
    source-dirs: main
    dependencies:
    - csillag-xmonad
  xmonadctl:
    main: xmonadctl.hs
    source-dirs: main
