name:                csillag-xmonad
version:             0.1.0.0
author:              "Daniel Csillag"
copyright:           "2021 Daniel Csillag"

description:         My XMonad configs

dependencies:
- base >= 4.7 && < 5
- xmonad >= 0.15
- xmonad-contrib >= 0.16
- containers
- directory

ghc-options:
- -Wall
- -Wno-missing-signatures
- -fwrite-ide-info # for weeder

library:
  source-dirs: src

executables:
  my-xmonad:
    main:                xmonad.hs
    source-dirs:         main
    dependencies:
    - csillag-xmonad
