#         _
#  _ __  (_)  ___  ___   _ __ ___
# | '_ \ | | / __|/ _ \ | '_ ` _ \
# | |_) || || (__| (_) || | | | | |
# | .__/ |_| \___|\___/ |_| |_| |_|
# |_|
#
# @what My Compton configuration.
# @author Daniel Csillag (aka. dccsillag)
#

backend = "glx";

vsync = true;
xrender-sync-fence = true;

# Fading
fading = false;
fade-delta = 2;
fade-in-step = 0.015;
fade-out-step = 0.015;
no-fading-openclose = false;

# Shadows
shadow = true;
shadow-radius = 10;
shadow-offset-x = -4;
shadow-offset-y = -4;
shadow-red = 0;
shadow-green = 0;
shadow-blue = 0;
shadow-opacity = 0.6;
crop-shadow-to-monitor = true;

# # Corners
corner-radius = 12;
# corner-radius = 5;
round-borders = 0;

blur: {
    method = "dual_kawase";
    strength = 5;
}

rules = (
    # === Animations ===
    { # Always matches
        animations = (
            {
                triggers = ["open", "show"];
                preset = "appear";
            },
            {
                triggers = ["close", "hide"];
                preset = "disappear";
            },
        );
    },
    { # Unless it's Rofi
        match = "class_g != 'Rofi'";

        animations = (
            {
                triggers = ["geometry"];
                preset = "geometry-change";
                # saved-image-blend
            },
        );
    },

    { # Don't do shadows on shaped windows:
        match = "bounding_shaped && !rounded_corners";
        shadow = false;
    },
    { # Don't do shadows on menus
        match = "window_type *= 'menu' || window_type *= 'dropdown' || window_type *= 'popup' || window_type *= 'tooltip' || role *= 'popup'";
        shadow = false;
        blur-background = false;
    },
    { # Eww bar
        match = "name = 'Eww - bar'";
        shadow = false;
        blur-background = false;
        corner-radius = 0;
    },
    { # Don't do shadows on Eww&xmonad stuff
        match = "name = 'Eww - bar' || name = 'Eww - volume' || name = 'Eww - brightness' || name = 'Eww - low-battery'";
        shadow = false;
        blur-background = false;
    },
    {  # Dim inactive windows
        match = "!focused && (class_g != 'Rofi' && name != 'KDE Connect Daemon' && name = 'as_toolbar' && name != '')";
        dim = 0.1;
    },
    {  # Misc blur fixes
        match = "class_g ?= 'zoom' || class_g = 'slop'";
        blur-background = false;
    },
    { # Terminal opacity
        match = "class_g = 'Alacritty' || class_g = 'kitty' || class_g = 'scratchterm' || class_g = 'sysmon' || class_g = 'audiomanage'";
        opacity = 0.9;
    }
)

# vim: ft=conf
